import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next JS API Request</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Generated by Peter Keck" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Next.js Request Demo</h1>
      <p>This page is a demo project and template for a development of a Server Side Renderer (SSR) project using Flask,
        which accesses an external API and caches the result in a cache.</p>
      <p>This comes with a responsive template using Bootstrap.</p>
      <h2 className="pt-3">Weather in Stuttgart</h2>
      <div className="weather_info text-center h2">current_weather</div>
    </>
  )
}

export default Home
